apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "postfix.fullname" . }}
  labels:
    app: {{ template "postfix.name" . }}
    chart: {{ template "postfix.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "postfix.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "postfix.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "postfix.name" . }}
        image: '{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}'
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: TX_SMTP_RELAY_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ template "postfix.fullname" . }}
              key: tx-smtp-relay-host
        - name: TX_SMTP_FALLBACK_RELAY_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ template "postfix.fullname" . }}
              key: tx-smtp-fallback-relay-host
        - name: TX_SMTP_RELAY_MYHOSTNAME
          valueFrom:
            configMapKeyRef:
              name: {{ template "postfix.fullname" . }}
              key: tx-smtp-relay-myhostname
        - name: TX_SMTP_RELAY_NETWORKS
          valueFrom:
            configMapKeyRef:
              name: {{ template "postfix.fullname" . }}
              key: tx-smtp-relay-networks
        - name: POSTFIX_CUSTOM_CONFIG
          valueFrom:
            configMapKeyRef:
              name: {{ template "postfix.fullname" . }}
              key: postfix-custom-config
        ports:
          - name: smtp
            containerPort: {{ .Values.service.port }}
        volumeMounts:
          - mountPath: /var/spool/postfix/
            name: metrics
          - mountPath: /data/log/
            name: logs
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
        - name: metrics
          emptyDir: {}
        - name: logs
          emptyDir: {}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
